const $=(s,e=document)=>e.querySelector(s); const $$=(s,e=document)=>[...e.querySelectorAll(s)];
const VERSION="3.2.0";
const THEME_NAMES={boy:"BOY · Action Manga",girl:"GIRL · Pop Manga",machine:"MACHINE · Cyber Grid",football:"FOOTBALL · Night Match"};
const THEME_KICKER={boy:"⚡ SPEED // FOCUS // HIT",girl:"✦ SPARK // FOCUS // HIT",machine:"[ TARGET_LOCK : READY ]",football:"⚽ MATCH TIMER // ONE SHOT"};
const CLOCK_NAMES={clean:"Clean",digital:"Green Digital",arcade:"Arcade",manga:"Manga Panel",analog:"Analog"};
const SOUND_NAMES={off:"Sound off",pulse:"1s Beat",focus:"0.5s Beat",target:"Target Rush"};
const chapters=["Warm-up","Rhythm","Control","Sharp","Pressure","Pro","Elite","Master","Insane","GOAT Zone"];
const state={
 theme:localStorage.getItem("hit_theme_v32")||localStorage.getItem("hit_theme_v3")||"boy",
 skin:localStorage.getItem("hit_skin_v32")||localStorage.getItem("hit_skin_v3")||"classic",
 clockStyle:localStorage.getItem("hit_clock_v32")||localStorage.getItem("hit_clock_v3")||"clean",
 soundMode:localStorage.getItem("hit_sound_v32")||localStorage.getItem("hit_sound_v3")||"off",
 clearedLevel:Number(localStorage.getItem("hit_cleared_v32") ?? localStorage.getItem("hit_unlocked_v3") ?? 0),
 levelStars:JSON.parse(localStorage.getItem("hit_level_stars_v32")||"{}"),
 mode:null,playerCount:2,players:[],targetMode:"5",freeTarget:4.2,target:5,currentPlayer:0,roundResults:[],
 level:1,levelTarget:2,started:false,startTime:0,raf:null,soundTimer:null,audioCtx:null,lastScreen:"home"
};
const skins=[
 {id:"classic",name:"Classic Red",unlock:0,preview:"🔴"},{id:"neon",name:"Neon Core",unlock:3,preview:"◉"},{id:"tiny",name:"Tiny Hit",unlock:5,preview:"•"},
 {id:"lightning",name:"Lightning",unlock:7,preview:"⚡"},{id:"football",name:"Football",unlock:10,preview:"⚽"},{id:"flower",name:"Flower",unlock:15,preview:"🌸"},
 {id:"poop",name:"Seriously?",unlock:20,preview:"💩"},{id:"unicorn",name:"Unicorn",unlock:28,preview:"🦄"},{id:"teddy",name:"Soft Mode",unlock:36,preview:"🧸"},
 {id:"chrome",name:"Chrome",unlock:42,preview:"◉"},{id:"bomb",name:"Bomb",unlock:48,preview:"💣"},{id:"cup",name:"Champions Cup",unlock:55,preview:"🏆"},
 {id:"meteor",name:"Meteor",unlock:65,preview:"☄️"},{id:"ice",name:"Ice",unlock:75,preview:"🧊"},{id:"crown",name:"Crown",unlock:85,preview:"👑"},
 {id:"star",name:"Star Burst",unlock:92,preview:"⭐"},{id:"goat",name:"GOAT",unlock:100,preview:"🐐"}
];
const nickPool=["Ace","Nova","Pixel","Echo","Jinx","Ghost","Turbo","Zero","Vibe","Flash","Nox","Orbit"];
const fmt=n=>Number(n).toFixed(2).replace(".",","); const signed=n=>Math.abs(n)<.005?"±0,00":`${n>0?"+":"−"}${fmt(Math.abs(n))}`;
const escapeHtml=(str="")=>str.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const randomTarget=()=> (Math.floor(Math.random()*140)+16)/10;
function levelTarget(level){ if(level===100)return 10.0; const v=16+((level*37+Math.floor(level/10)*17)%140); return Math.min(155,v)/10; }
function lerp(a,b,t){return a+(b-a)*t}
function levelLimit(level){
 const zones=[[1,10,.45,.32],[11,25,.30,.22],[26,40,.20,.16],[41,55,.15,.12],[56,70,.11,.09],[71,85,.08,.06],[86,95,.05,.04],[96,100,.03,.02]];
 const z=zones.find(x=>level>=x[0]&&level<=x[1]); const t=z[0]===z[1]?1:(level-z[0])/(z[1]-z[0]); return Math.round(lerp(z[2],z[3],t)*100)/100;
}
function difficulty(level){return ["ROOKIE","RHYTHM","SHARP","PRESSURE","PRO","ELITE","MASTER","INSANE","GOAT"][Math.min(8,Math.floor((level-1)/12))]}
function availableMaxLevel(){return Math.min(100,state.clearedLevel+1)}
function starsFor(absDiff,limit){if(absDiff<=limit*.25)return 3;if(absDiff<=limit*.6)return 2;return 1}
function totalStars(){return Object.values(state.levelStars).reduce((a,b)=>a+Number(b||0),0)}
function saveProgress(){localStorage.setItem("hit_cleared_v32",String(state.clearedLevel));localStorage.setItem("hit_level_stars_v32",JSON.stringify(state.levelStars))}
function commentFor(d){const p=[[.001,["Exakt. Mehr geht nicht.","0,00. Respekt.","Perfekt getroffen."]],[.03,["Unverschämt präzise.","Timing auf Anschlag.","Das war richtig stark."]],[.06,["Sehr stark. Fast perfekt.","Sauber getroffen.","Das sitzt."]],[.10,["Richtig eng.","Kaum Luft dazwischen.","Sehr sauber."]],[.18,["Starkes Timing.","Knapp. Und zwar richtig.","Das kann sich sehen lassen."]],[.30,["Guter Hit.","Solide unter Druck.","Sauber. Noch etwas Feinschliff."]],[.50,["Ordentlich. Aber noch kein Flex.","Solide. Nächster wird enger.","Gut drin."]],[.8,["Noch okay. Fokus.","War drin. Aber nicht knapp.","Da geht mehr."]],[1.2,["Eher Gefühl als Timing.","Der Moment war da. Du etwas später.","Nicht dein bester Hit."]],[2,["Der Button war ziemlich groß.","Mutig. Präzise eher nicht.","Kreative Zeitrechnung."]],[Infinity,["Komplett eigene Zeitzone.","Das war kein Hit. Das war ein Ausflug.","Selbstvertrauen: stark. Timing: schwierig."]]];for(const [l,a] of p)if(d<=l)return a[Math.floor(Math.random()*a.length)]}
function setTheme(v){state.theme=v;document.body.dataset.theme=v;localStorage.setItem("hit_theme_v32",v)}
function setClock(v){state.clockStyle=v;document.body.dataset.clock=v;localStorage.setItem("hit_clock_v32",v)}
function setSound(v){state.soundMode=v;localStorage.setItem("hit_sound_v32",v)}
function skinAvailable(id){const s=skins.find(x=>x.id===id);return s&&state.clearedLevel>=s.unlock}
function setSkin(id){if(skinAvailable(id)){state.skin=id;localStorage.setItem("hit_skin_v32",id)}}
function nextUnlock(){return skins.find(s=>s.unlock>state.clearedLevel)}
function stopTimer(){state.started=false;if(state.raf)cancelAnimationFrame(state.raf);state.raf=null;if(state.soundTimer)clearTimeout(state.soundTimer);state.soundTimer=null}
function setNav(key){$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===key))}
function setBack(show=true){$('#backBtn').classList.toggle('hidden',!show)}
function ensureAudio(){if(!state.audioCtx){const C=window.AudioContext||window.webkitAudioContext;if(C)state.audioCtx=new C()}if(state.audioCtx?.state==='suspended')state.audioCtx.resume()}
function beep(freq=680,dur=.045,type='sine',gain=.03){try{ensureAudio();if(!state.audioCtx)return;const o=state.audioCtx.createOscillator(),g=state.audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(state.audioCtx.destination);o.start();o.stop(state.audioCtx.currentTime+dur)}catch{}}
function scheduleSound(target){if(state.soundMode==='off')return;const loop=()=>{if(!state.started)return;const e=(performance.now()-state.startTime)/1000;let int=1000,f=680,type='sine';if(state.soundMode==='focus'){int=500;f=620;type='triangle'}if(state.soundMode==='target'){const r=Math.max(0,target-e);if(r>4){int=900;f=500}else if(r>2){int=600;f=620}else if(r>1){int=340;f=760}else if(r>.5){int=190;f=900}else{int=110;f=1050}type='square'}beep(f,.04,type,.03);state.soundTimer=setTimeout(loop,int)};loop()}
function animateMeter(d,max=1){const e=$('#meterFill');if(!e)return;const p=Math.max(4,100-(Math.min(d,max)/max)*100);requestAnimationFrame(()=>e.style.width=`${p}%`)}
function lockNext(btn,ms=1450){btn.disabled=true;const t=btn.textContent;btn.textContent='KURZ ANSCHAUEN…';setTimeout(()=>{if(document.body.contains(btn)){btn.disabled=false;btn.textContent=t}},ms)}

function renderHome(){stopTimer();state.lastScreen='home';state.mode=null;setBack(false);setNav('home');$('#screen').innerHTML=$('#home-template').innerHTML;setTheme(state.theme);setClock(state.clockStyle);$('#themeKicker').textContent=THEME_KICKER[state.theme];$('#currentThemeTag').textContent=THEME_NAMES[state.theme];$('#currentClockTag').textContent=`Uhr · ${CLOCK_NAMES[state.clockStyle]}`;$('#currentSoundTag').textContent=SOUND_NAMES[state.soundMode];$('#homeProgress').textContent=`${state.clearedLevel}/100`;$('#homeStars').textContent=`${totalStars()} / 300`;const st=$('#homeStatus');st.textContent='prüft …';Promise.resolve(HitScores.ready).finally(()=>{const e=$('#homeStatus');if(e)e.textContent=HitScores.provider==='firebase'?'ONLINE':'FALLBACK'});const n=nextUnlock();$('#nextUnlock').innerHTML=n?`Nächster Unlock: <strong>${n.preview} ${n.name}</strong> bei Level ${n.unlock}.`:`<strong>Alles freigeschaltet.</strong> GOAT collection complete.`;$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>b.dataset.mode==='level'?renderLevelMap():renderPartySetup()))}

function renderSettings(){stopTimer();state.lastScreen='settings';setBack(true);setNav('settings');$('#screen').innerHTML=`<h1 class="screen-title">SETTINGS</h1><p class="screen-sub">Vier Welten, fünf Uhren, vier Sound-Hilfen. Alles bleibt lokal gespeichert.</p>
<section class="panel"><div class="panel-head"><h2>Style World</h2><span class="muted">bewusst deutlich verschieden</span></div><div class="settings-grid">
<button class="theme-card ${state.theme==='boy'?'active':''}" data-theme-choice="boy"><span class="theme-symbol">⚡</span><strong>BOY</strong><small>Action Manga · Blau · Speedlines · kantiger Look</small></button>
<button class="theme-card ${state.theme==='girl'?'active':''}" data-theme-choice="girl"><span class="theme-symbol">♡</span><strong>GIRL</strong><small>Pop Manga · Pink/Violett · Sparkles · softer Look</small></button>
<button class="theme-card ${state.theme==='machine'?'active':''}" data-theme-choice="machine"><span class="theme-symbol">⌁</span><strong>MACHINE</strong><small>Cyber Grid · Terminal · Cyan · technisch</small></button>
<button class="theme-card ${state.theme==='football'?'active':''}" data-theme-choice="football"><span class="theme-symbol">⚽</span><strong>FOOTBALL</strong><small>Night Match · Spielfeld · Grün/Gold · Scoreboard</small></button></div></section>
<section class="panel"><div class="panel-head"><h2>Button Collection</h2><span class="muted">${state.clearedLevel}/100 Progress</span></div><div id="skinGrid" class="skin-grid"></div></section>
<section class="panel"><div class="panel-head"><h2>Uhr</h2><span class="muted">gleiche Messung, anderer Look</span></div><div class="clock-grid">
${[['clean','00,00','Clean'],['digital','88:88','Digital'],['arcade','◢','Arcade'],['manga','ドン!','Manga'],['analog','🕘','Analog']].map(x=>`<button class="clock-card ${state.clockStyle===x[0]?'active':''}" data-clock="${x[0]}"><div class="clock-preview">${x[1]}</div><div class="clock-name">${x[2]}</div></button>`).join('')}</div></section>
<section class="panel"><div class="panel-head"><h2>Sound Assist</h2><span class="muted">jederzeit abschaltbar</span></div><div class="sound-grid">
${[['off','🔇','Off'],['pulse','• • •','1s Beat'],['focus','••••','0.5s Beat'],['target','↗','Target Rush']].map(x=>`<button class="sound-card ${state.soundMode===x[0]?'active':''}" data-sound="${x[0]}"><div class="sound-preview">${x[1]}</div><div class="sound-name">${x[2]}</div></button>`).join('')}</div><p class="muted" style="margin:12px 0 0">Target Rush wird dichter, je näher du an die Zielzeit kommst.</p></section>`;
renderSkinGrid();$$('[data-theme-choice]').forEach(b=>b.addEventListener('click',()=>{setTheme(b.dataset.themeChoice);renderSettings()}));$$('[data-clock]').forEach(b=>b.addEventListener('click',()=>{setClock(b.dataset.clock);renderSettings()}));$$('[data-sound]').forEach(b=>b.addEventListener('click',()=>{setSound(b.dataset.sound);beep(740,.04);renderSettings()}))}
function renderSkinGrid(){const g=$('#skinGrid');if(!g)return;g.innerHTML=skins.map(s=>{const lock=!skinAvailable(s.id);return `<button class="skin-card ${state.skin===s.id?'active':''}" data-skin="${s.id}" ${lock?'disabled':''}>${lock?`<span class="lock">🔒 L${s.unlock}</span>`:''}<div class="skin-preview">${s.preview}</div><div class="skin-name">${s.name}</div></button>`}).join('');$$('[data-skin]').forEach(b=>b.addEventListener('click',()=>{setSkin(b.dataset.skin);renderSkinGrid()}))}

function renderLevelMap(chapterIndex=Math.floor((availableMaxLevel()-1)/10)){stopTimer();state.lastScreen='levels';state.mode='level';setBack(true);setNav('levels');chapterIndex=Math.max(0,Math.min(9,chapterIndex));const start=chapterIndex*10+1;const end=start+9;$('#screen').innerHTML=`<h1 class="screen-title">LEVEL MAP</h1><p class="screen-sub">100 Level in 10 Kapiteln. Bereits erreichte Level kannst du jederzeit erneut spielen.</p>
<section class="panel"><div class="chapter-row">${chapters.map((c,i)=>`<button class="chapter-btn ${i===chapterIndex?'active':''}" data-chapter="${i}">${i+1} · ${c}</button>`).join('')}</div>
<div class="chapter-title"><div><span class="muted">KAPITEL ${chapterIndex+1}</span><br><strong>${chapters[chapterIndex]}</strong></div><span class="difficulty-badge">${difficulty(start)}</span></div><div class="progress-line"><span style="width:${state.clearedLevel}%"></span></div>
<div class="level-grid">${Array.from({length:10},(_,i)=>{const lv=start+i,unlocked=lv<=availableMaxLevel(),cleared=lv<=state.clearedLevel,stars=state.levelStars[lv]||0;return `<button class="level-btn ${cleared?'cleared':''} ${!unlocked?'locked':''}" data-level="${lv}" ${!unlocked?'disabled':''}><strong>${lv}</strong><small>${fmt(levelTarget(lv))}s · ±${fmt(levelLimit(lv))}</small><span class="stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</span></button>`}).join('')}</div></section>
<section class="panel"><div class="panel-head"><h2>Progress</h2><span class="muted">${state.clearedLevel}/100 · ${totalStars()} Sterne</span></div><div class="actions"><button id="continueLevel" class="primary">WEITER BEI LEVEL ${availableMaxLevel()}</button><button id="levelOne" class="secondary">LEVEL 1</button></div></section>`;$$('[data-chapter]').forEach(b=>b.addEventListener('click',()=>renderLevelMap(Number(b.dataset.chapter))));$$('[data-level]').forEach(b=>b.addEventListener('click',()=>startLevel(Number(b.dataset.level))));$('#continueLevel').addEventListener('click',()=>startLevel(availableMaxLevel()));$('#levelOne').addEventListener('click',()=>startLevel(1))}
function startLevel(lv){state.mode='level';state.level=lv;state.levelTarget=levelTarget(lv);renderGame()}

function renderPartySetup(){stopTimer();state.lastScreen='round';state.mode='party';setBack(true);setNav('round');$('#screen').innerHTML=`<h1 class="screen-title">HIT! ROUND</h1><p class="screen-sub">Gleiche Zielzeit für alle. Kleinste Abweichung gewinnt.</p><div class="setup-grid"><section class="panel"><h2>Spieler</h2><div class="choice-row">${[1,2,3,4,5,6].map(n=>`<button class="choice ${state.playerCount===n?'active':''}" data-count="${n}">${n}</button>`).join('')}</div></section><section class="panel"><h2>Zielzeit</h2><div class="choice-row">${['2','3','5','10'].map(v=>`<button class="choice ${state.targetMode===v?'active':''}" data-target="${v}">${v}s</button>`).join('')}<button class="choice ${state.targetMode==='random'?'active':''}" data-target="random">ZUFALL</button><button class="choice ${state.targetMode==='free'?'active':''}" data-target="free">FREI</button></div><div id="freeWrap" style="margin-top:12px;${state.targetMode==='free'?'':'display:none'}"><input id="freeTarget" class="input" type="number" min="1.5" max="99.99" step="0.01" value="${state.freeTarget}"></div></section></div><section class="panel"><h2>Namen</h2><div id="playerList" class="player-list"></div><div class="actions"><button id="mixNames" class="secondary">NICKS MISCHEN</button></div></section><div class="actions"><button id="startRound" class="primary">RUNDE STARTEN →</button></div>`;renderPlayers();$$('[data-count]').forEach(b=>b.addEventListener('click',()=>{state.playerCount=Number(b.dataset.count);renderPartySetup()}));$$('[data-target]').forEach(b=>b.addEventListener('click',()=>{state.targetMode=b.dataset.target;renderPartySetup()}));$('#mixNames').addEventListener('click',()=>{state.players=[...nickPool].sort(()=>Math.random()-.5).slice(0,state.playerCount);renderPlayers()});$('#startRound').addEventListener('click',()=>{state.players=$$('.playerName').map((e,i)=>e.value.trim()||`Player ${i+1}`);if(state.targetMode==='random')state.target=randomTarget();else if(state.targetMode==='free'){const v=Number($('#freeTarget').value);state.target=Math.max(1.5,Math.min(99.99,Number.isFinite(v)?v:5));state.freeTarget=state.target}else state.target=Number(state.targetMode);state.currentPlayer=0;state.roundResults=[];renderGame()})}
function renderPlayers(){const l=$('#playerList');let a=state.players.slice(0,state.playerCount);while(a.length<state.playerCount)a.push(nickPool[a.length]||`Player ${a.length+1}`);state.players=a;l.innerHTML=a.map((n,i)=>`<input class="input playerName" maxlength="16" value="${escapeHtml(n)}" placeholder="Player ${i+1}">`).join('')}

function timerMarkup(){if(state.clockStyle!=='analog')return `<div id="timer" class="timer">0,00<small>s</small></div>`;return `<div id="timer" class="timer"></div><div class="analog-face">${Array.from({length:12},(_,i)=>`<span class="tick" style="transform:translate(-50%,-100%) rotate(${i*30}deg)"></span>`).join('')}<span class="analog-hand analog-minor" id="analogMinute"></span><span class="analog-hand analog-sec" id="analogSecond"></span><span class="analog-center"></span></div><div class="analog-label" id="analogLabel">0,00 s</div>`}
function buzzerInner(){const m={lightning:'⚡',football:'⚽',flower:'🌸',poop:'💩',unicorn:'🦄',teddy:'🧸',bomb:'💣',cup:'🏆',meteor:'☄️',ice:'🧊',crown:'👑',star:'⭐',goat:'🐐'};return m[state.skin]||'<span id="buzzerLabel" class="buzzer-label">START</span>'}
function renderGame(){stopTimer();state.started=false;setBack(true);const target=state.mode==='level'?state.levelTarget:state.target;const name=state.mode==='level'?`LEVEL ${state.level}`:state.players[state.currentPlayer];$('#screen').innerHTML=`<section class="game-wrap"><div class="game-meta"><span class="pill">${escapeHtml(name)}</span>${state.mode==='party'?`<span class="pill">${state.currentPlayer+1}/${state.playerCount}</span>`:`<span class="pill">${difficulty(state.level)}</span>`}<span class="pill">${SOUND_NAMES[state.soundMode]}</span></div>${state.mode==='level'?`<div class="progress-line"><span style="width:${state.level}%"></span></div><div class="level-rule">Grenze: ±${fmt(levelLimit(state.level))} s · Best: ${state.levelStars[state.level]||0}/3 Sterne</div>`:''}<div class="target-label">TARGET</div><div class="target">${fmt(target)} s</div><div class="timer-box">${timerMarkup()}</div><div class="buzzer-wrap"><button id="buzzer" class="buzzer ${state.skin}">${buzzerInner()}</button></div><div id="statusLine" class="status-line">Erster Tap startet. Zweiter Tap stoppt.</div></section>`;$('#buzzer').addEventListener('pointerdown',e=>{e.preventDefault();state.started?finishHit():startHit()},{passive:false})}
function updateTimer(e){const d=fmt(e);if(state.clockStyle!=='analog'){const t=$('#timer');if(t)t.innerHTML=`${d}<small>s</small>`}else{if($('#analogLabel'))$('#analogLabel').textContent=`${d} s`;if($('#analogSecond'))$('#analogSecond').style.transform=`translate(-50%,-92%) rotate(${e*360}deg)`;if($('#analogMinute'))$('#analogMinute').style.transform=`translate(-50%,-92%) rotate(${e*36}deg)`}}
function startHit(){state.started=true;state.startTime=performance.now();if($('#buzzerLabel'))$('#buzzerLabel').textContent='HIT!';$('#statusLine').textContent='Jetzt zählt dein Timing.';scheduleSound(state.mode==='level'?state.levelTarget:state.target);const tick=()=>{if(!state.started)return;updateTimer((performance.now()-state.startTime)/1000);state.raf=requestAnimationFrame(tick)};state.raf=requestAnimationFrame(tick)}
function finishHit(){const e=(performance.now()-state.startTime)/1000;stopTimer();const result=Math.round(e*100)/100,target=state.mode==='level'?state.levelTarget:state.target,diff=Math.round((result-target)*100)/100,abs=Math.abs(diff);beep(1200,.06,'triangle',.04);if(state.mode==='level')renderLevelResult(result,diff,abs);else{state.roundResults.push({name:state.players[state.currentPlayer],target,result,diff,absDiff:abs});renderPartyResult(result,diff,abs)}}
function renderLevelResult(result,diff,abs){const lim=levelLimit(state.level),passed=abs<=lim+.0001,stars=passed?starsFor(abs,lim):0;let unlock='';if(passed){state.levelStars[state.level]=Math.max(Number(state.levelStars[state.level]||0),stars);if(state.level>state.clearedLevel){state.clearedLevel=state.level;const newly=skins.filter(s=>s.unlock===state.clearedLevel);if(newly.length)unlock=`Neue Button-Skin: ${newly.map(x=>`${x.preview} ${x.name}`).join(', ')}`;saveProgress()}}const exact=state.level===100&&abs===0;$('#screen').innerHTML=`<section class="panel result-card"><div class="target-label">LEVEL ${state.level}</div><div class="result-big">${fmt(result)}</div><div class="result-diff">${signed(diff)} s</div><div class="result-stars">${passed?'★'.repeat(stars)+'☆'.repeat(3-stars):'☆☆☆'}</div><div class="result-comment">${passed?(exact?'0,00 im Finale. GOAT.':commentFor(abs)):'Noch nicht. Level bleibt offen.'}</div><div class="result-detail">Target ${fmt(state.levelTarget)} s · Grenze ±${fmt(lim)} s · Abweichung ${fmt(abs)} s</div><div class="result-meter"><span id="meterFill"></span></div>${unlock?`<div class="unlock-toast">${unlock}</div>`:''}<div class="actions" style="justify-content:center"><button id="levelNext" class="primary">${passed?(state.level===100?'FINISH →':'NÄCHSTES LEVEL →'):'NOCHMAL →'}</button><button id="levelMap" class="secondary">LEVEL MAP</button></div></section>`;animateMeter(abs,Math.max(.45,lim*2));const b=$('#levelNext');lockNext(b,1600);b.addEventListener('click',()=>{if(!passed)return renderGame();if(state.level===100)return renderLevelFinish(exact);startLevel(state.level+1)});$('#levelMap').addEventListener('click',()=>renderLevelMap(Math.floor((state.level-1)/10)))}
function renderLevelFinish(exact){state.clearedLevel=100;saveProgress();$('#screen').innerHTML=`<section class="panel result-card"><div class="target-label">100/100 COMPLETE</div><div class="result-big">${exact?'🐐':'100'}</div><div class="result-comment">${exact?'Perfektes Finale. GOAT STATUS.':'Alle 100 Level geschafft.'}</div><div class="result-detail">${totalStars()} von 300 möglichen Sternen.</div><div class="unlock-toast">🐐 GOAT Button freigeschaltet.</div><div class="actions" style="justify-content:center"><button id="mapFinish" class="primary">LEVEL MAP</button><button id="homeFinish" class="secondary">HOME</button></div></section>`;$('#mapFinish').addEventListener('click',()=>renderLevelMap(9));$('#homeFinish').addEventListener('click',renderHome)}
function renderPartyResult(result,diff,abs){const label=state.currentPlayer+1<state.playerCount?'NÄCHSTER →':'AUSWERTUNG →';$('#screen').innerHTML=`<section class="panel result-card"><div class="target-label">${escapeHtml(state.players[state.currentPlayer])}</div><div class="result-big">${fmt(result)}</div><div class="result-diff">${signed(diff)} s</div><div class="result-comment">${commentFor(abs)}</div><div class="result-detail">Target ${fmt(state.target)} s · Abweichung ${fmt(abs)} s</div><div class="result-meter"><span id="meterFill"></span></div><div class="actions" style="justify-content:center"><button id="roundNext" class="primary">${label}</button></div></section>`;animateMeter(abs,1);const b=$('#roundNext');lockNext(b,1500);b.addEventListener('click',()=>{state.currentPlayer++;state.currentPlayer<state.playerCount?renderGame():finishRound()})}
async function finishRound(){const ranked=[...state.roundResults].sort((a,b)=>a.absDiff-b.absDiff);await HitScores.save(ranked.map(r=>({...r,theme:state.theme,createdAt:new Date().toISOString()})));$('#screen').innerHTML=`<h1 class="screen-title">ROUND RESULT</h1><p class="screen-sub">Target ${fmt(state.target)} s</p><section class="panel"><div class="ranking">${ranked.map((r,i)=>`<div class="rank-row"><div class="rank-pos">${i+1}.</div><div class="rank-name">${escapeHtml(r.name)} ${i===0?'<span class="badge">BEST HIT</span>':''}</div><div class="rank-score">${fmt(r.result)} s<br><span class="muted">${signed(r.diff)} s</span></div></div>`).join('')}</div></section><section class="panel result-card"><div class="result-comment">${escapeHtml(ranked[0].name)} holt die Runde.</div><div class="result-detail">${fmt(ranked[0].absDiff)} s Abweichung. ${ranked.length>1?`${escapeHtml(ranked.at(-1).name)} braucht die Revanche.`:''}</div></section><div class="actions"><button id="again" class="primary">NOCHMAL</button><button id="homeRound" class="secondary">HOME</button></div>`;$('#again').addEventListener('click',()=>{state.currentPlayer=0;state.roundResults=[];if(state.targetMode==='random')state.target=randomTarget();renderGame()});$('#homeRound').addEventListener('click',renderHome)}

async function renderScores(filter='all'){stopTimer();state.lastScreen='scores';setBack(true);setNav('scores');const all=await HitScores.top(120),now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),week=new Date(today),day=(week.getDay()+6)%7;week.setDate(week.getDate()-day);const scores=all.filter(s=>{const d=new Date(s.createdAt);if(filter==='today')return d>=today;if(filter==='week')return d>=week;return true}).slice(0,40);const online=HitScores.provider==='firebase';$('#screen').innerHTML=`<h1 class="screen-title">HIGHSCORES</h1><p class="screen-sub"><span class="${online?'online-dot':'online-dot offline-dot'}"></span>${online?'ONLINE · gemeinsame Rangliste':'OFFLINE · lokaler Fallback'}</p><section class="panel"><div class="choice-row" style="margin-bottom:18px"><button class="choice ${filter==='all'?'active':''}" data-filter="all">ALL TIME</button><button class="choice ${filter==='today'?'active':''}" data-filter="today">HEUTE</button><button class="choice ${filter==='week'?'active':''}" data-filter="week">DIESE WOCHE</button></div>${scores.length?`<div class="score-table">${scores.map((s,i)=>{const d=new Date(s.createdAt);return `<div class="score-row"><strong>${i+1}.</strong><div><strong>${escapeHtml(s.name)}</strong><br><span class="muted">Target ${fmt(s.target)} · Hit ${fmt(s.result)}</span></div><strong>${fmt(s.absDiff)} s</strong><span class="score-date muted">${d.toLocaleDateString('de-DE')}</span></div>`}).join('')}</div>`:'<div class="empty">Noch kein Highscore in diesem Zeitraum.</div>'}</section>`;$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>renderScores(b.dataset.filter)))}

function goBack(){if(state.started){stopTimer();}if(state.lastScreen==='settings'||state.lastScreen==='scores'||state.lastScreen==='round'||state.lastScreen==='levels')renderHome();else renderHome()}
$('#backBtn').addEventListener('click',goBack);$('#settingsBtn').addEventListener('click',renderSettings);$('#scoreBtn').addEventListener('click',()=>renderScores('all'));
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>{const n=b.dataset.nav;if(n==='home')renderHome();if(n==='levels')renderLevelMap();if(n==='round')renderPartySetup();if(n==='scores')renderScores('all');if(n==='settings')renderSettings()}));
setTheme(state.theme);setClock(state.clockStyle);if(!skinAvailable(state.skin))state.skin='classic';renderHome();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=3.2.0').catch(()=>{}));
